site_name: Crispy Waffle
logo: logo.png
repo_url: https://github.com/guibranco/crispywaffle
extra_css: [extra.css]
theme:
  namw: readthedocs
  icon:
    repo: fontawesome/brands/github
plugins:
  - git-authors
  - git-committers:
      repository: guibranco/CrispyWaffle
      branch: main

